# Send Command to South Bound endpoint - Nokia SMF
- name: Create the list
  set_fact:   
    list_smf_dnnName: "{{ smf_dnnName.split(',')| map('trim')| list }}" 
    # list_amfSlice_dnnName: "{{ amfSlice_dnnName.split(',') | list }}" 

- name: Creates directory
  file:
    path: /tmp/ansible_log
    state: directory
    mode: 0775

- name: setting filename
  set_fact:
    filename: /tmp/ansible_log/ansible_{{ ansible_date_time.iso8601 }}.log

- shell: "python3 test.py"
  register: start_time
  no_log: true


- name: generate SB json and copy it to utility server
  copy:
    dest: "/tmp/smf_provide_{{ instance_name }}.sh"
    content: |
        #!/usr/bin/expect
        spawn ssh {{ SMF_USER }}@{{ SMF_IP }} -p {{ SMF_PORT }}
        expect "password: "
        send "{{ SMF_PASS }}\r"
        expect eof 

- name: Insert a line at the end of a file.
  lineinfile:
    path: "/tmp/smf_provide_{{ instance_name }}.sh"
    line: |
            send "configure mobile-gateway profile list slice-instance-list {{ smfSlice_sliceInstanceListName }}\r"
            send "exit\r"
            send "configure mobile-gateway profile list slice-instance-list {{ smfSlice_sliceInstanceListName }} slice-instance dish_slice_instance\r"
            send "configure mobile-gateway profile list slice-list {{ smfSlice_sliceListName }} slice {{ smfSlice_sliceName }} sst {{ smfSlice_sst }} sd {{ smfSlice_sd }} slice-instances {{ smfSlice_sliceInstanceListName }}\r"
            send "configure mobile-gateway pdn 5 instance-type user\r"
            send "configure mobile-gateway pdn 5 slices slice-list {{ smfSlice_sliceListName }}\r"
            send "configure mobile-gateway pdn 5 slices slice-instance-list {{ smfSlice_sliceInstanceListName }}\r"

- name: Insert a line at the end of a file.
  lineinfile:
    path: "/tmp/smf_provide_{{ instance_name }}.sh"
    line: send "configure mobile-gateway pdn 5 apn {{ item }} slices slice-list {{ smfSlice_sliceListName }}\r"
  loop: "{{ list_smf_dnnName }}"

- name: Insert a line at the end of a file.
  lineinfile:
    path: "/tmp/smf_provide_{{ instance_name }}.sh"
    line: send "exit all\r"

- name: Insert a line at the end of a file.
  lineinfile:
    path: "/tmp/smf_provide_{{ instance_name }}.sh"
    line: expect eof

# - name: Insert a line at the end of a file.
#   lineinfile:
#     path: "/tmp/smf_{{ instance_name }}.sh"
#     line: exit all
# - name: Insert a line at the end of a file.
  # lineinfile:
    # path: "/tmp/smf.txt"
    # line: slice-instance-list "{{ smfSlice_sliceInstanceListName}}"

#- name: shell command
#  shell: "sh /home/smf2.sh > smf_log.txt "
   #    args:
#    executable: /bin/bash

# - name: running script
  # command: chmod 775 smf_{{ instance_name }}.sh
# - name: running script
  # command: ./smf_{{ instance_name }}.sh
  # register: result

# - debug: var=result

- shell: "python3 test.py"
  register: end_time
  no_log: True

# - debug: msg="{{ result.date  }}"

- shell: "python3 diff.py '{{ end_time.stdout }}' '{{ start_time.stdout }}'"
  register: time_diff

- name: generate SB json and copy       
  copy:
    dest: "{{ filename }}"
    content: |
       ***********************************
       start_time:  {{ start_time.stdout }}
       end_time:  {{ end_time.stdout }}
       time_taken:  {{ time_diff.stdout }}
       ***********************************
       order_send:  {{lookup('file', '/tmp/smf_provide_{{ instance_name }}.sh')}}
       ____________________________________________________
