---
- name: uninstall
  hosts: localhost
  connection: local
  gather_facts: False
  # roles:
  #   - role: ../roles/delete
  tasks:

    - name: VoiceBundle Provide Role
      include_role:
        name: ../roles/delete
      when: "cnfInstance['custom_fields']['amfConfig'] !=None"
  # roles:
  #   - { role: ../roles/delete, when: Loopback == 'false' }