
- name: Creates directory
  file:
    path: /tmp/ansible_log
    state: directory
    mode: 0775

- name: setting filename
  set_fact:
    filename: /tmp/ansible_log/ansible_{{ extOrderId }}_{{ ansible_date_time.iso8601 }}.log
    listrequestedServices: "{{ requestedServices.split(',') | map('trim') |  list }}"
- shell: "python3 test.py"
  register: start_time
#  no_log: True    



- name: generate SB json and copy it to ansible POD
  template:
    src: bundle.json.j2
    dest: /tmp/bundle_{{ instance_name }}_{{ ansible_date_time.epoch|int }}.json
    
- name: Call RestAPI of SPML Adapter
  uri:
    url:  "{{ ansible_env.PGW_ADA_HOST }}/dish/ProvSpml/api/v1/spmlAdapter/modifyAddRequest"
    method: POST
    body: "{{lookup('template', 'bundle.json.j2')}}"
    status_code: 200
    body_format: json
    headers:
      content-type: "application/json"
      Returnresult_SMSProvideType: "FULL"
      return_content: yes
  register: result_SMSProvide
  ignore_errors: yes
  
- name: Check that url returns a status_code 200 and fail if status_code 200 is not returns
  fail:
    msg: Instance creation failed with error code {{ result_SMSProvide.status }} and error message {{ result_SMSProvide.json.error.message }}
  when:  result_SMSProvide.status!=200 and result_SMSProvide.json is defined

- name: Check that url returns a status_code 200 and fail if status_code 200 is not returns
  fail:
    msg: Instance creation failed with error code {{ result_SMSProvide.status }} and error message {{ result_SMSProvide.msg }}
  when: result_SMSProvide.status != 200


- shell: "python3 test.py"
  register: end_time
#  no_log: True

- shell: "python3 diff.py '{{ end_time.stdout }}' '{{ start_time.stdout }}'"
  register: time_diff
#  no_log: True

- name: generate SB json and copy       
  copy:
    dest: "{{ filename }}"
    content: |
       ***********************************
       start_time:  {{ start_time.stdout }}
       end_time:  {{ end_time.stdout }}
       time_taken:  {{ time_diff.stdout }}
       ***********************************
       order_send:  {{lookup('template', 'bundle.json.j2')}}
       ____________________________________________________
       result_SMSProvide_return: {{ result_SMSProvide.json }}  
  

- name: fail instance if there is a failure from SBI
  fail:
    msg: Instance creation failed with error code {{ result_SMSProvide.json.output.errorcode }} and error message {{ result_SMSProvide.json.output.message }}
  when: result_SMSProvide.json.output.result == "Failure"
