# convert ALM properties to json provide request for South Bound endpoint - Nokia Provisioning GW 
# - name: Creates directory
  # file:
    # path: /tmp/ansible_log
    # state: directory
    # mode: 0775

# - name: setting filename
  # set_fact:
    # filename: /tmp/ansible_log/ansible_{{ extOrderId }}_{{ ansible_date_time.iso8601 }}.log
    # listrequestedServices: "{{ requestedServices.split(',') | map('trim') |  list }}"

#-----------------------> Start time from system  <----------------------------  
- name: "##ALM##Get timestamp from the system"
  shell: "date +%Y-%m-%d%H:%M:%S.%5N"
  register: stime

#-----------------------> Print Start time  <----------------------------
- name: "##ALM##Start time"
  debug: msg="{{ stime }}"

# - name: setting filename
  # set_fact:
    # filename: /tmp/ansible_log/ansible_{{ extOrderId }}_pgw_provide.log
    
# - name: setting filename
  # set_fact:
    # filename: /tmp/ansible_log/ansible_{{ extOrderId }}.log
    # listrequestedServices: "{{ requestedServices.split(',') | map('trim') |  list }}"

# - name: Call Soap of SPML Adapter
  # uri:
    # url: "{{ PGW_ADA_HOST }}/service"
    # method: POST
    # body: "{{lookup('template', 'nokia_pgw_provide.xml.j2')}}"
    # body_format: "got:xml"
    # retry_count: "{{ ansible_env.RETRY_COUNT }}"
    # retry_interval: "{{ ansible_env.RETRY_INTERVAL }}"

#----------------------->Set Pgw url    <----------------------------
- name: "##ALM## setting PGW url"
  set_fact:
    pgw_url: "{{ deployment_location.properties.pgw_url }}"  


#-------------------> SOAP call for PGW provide_Voice only operation for Primary URL <------------------------
- name: "##PGW##Call Soap of SPML Adapter"
  environment:
    SSL_CERT_FILE: "/var/ald/pgw/pgw.cert"
  uri:
    url: "{{ pgw_url }}"
    method: POST
    body: "{{lookup('template', 'nokia_pgw_provide.xml.j2')}}"
    #status_code: [200,201]
    validate_certs: no
    return_content: yes
    headers:
      content-type: "text/xml"
      SOAPAction: ""
  register: result
  until: result.status == 200
  retries: "{{ RETRY_COUNT }}"
  delay: "{{ RETRY_INTERVAL }}"
  failed_when: "result.status not in [-1,200]"

#----------------> SOAP call for PGW provide_Voice only operation for Secondary URL <-----------------
- name: "##ALM## Call for PGW provide_Voice operation for Secondary URL"
  include_tasks: second.yaml
  when: result.status == -1

#-----------------------> End time from system  <----------------------------  
- name: "##ALM##Get timestamp from the system"
  shell: "date +%Y-%m-%d%H:%M:%S.%5N"
  register: etime

#-----------------------> Print End time  <----------------------------
- name: "##ALM##end time"
  debug: msg="{{ etime }}"

# - name: setting filename
  # set_fact:
    # filename: /tmp/ansible_log/ansible_{{ extOrderId }}_pgw_provide.log

# - name: generate SB json and copy       
  # copy:
    # dest: "{{ filename }}"
    # content: |
       # ***********************************
       # start_time:  {{ stime.start }}
       # end_time:  {{ etime.end }}
       # ***********************************
       # order_send:  {{lookup('template', 'nokia_pgw_provide.xml.j2')}}
       # ____________________________________________________
       # result_return: {{ result }}

- set_fact:
    target: "{{ result.content | regex_search('error') }}"

#-----------------------> Store request/response Logs in Eventlogger  <----------------------------
- name: "##ALM##Store request and response in DB"
  uri:
    url: "{{ deployment_location.properties.eventlogger_url }}"
    method: POST
    body: "{{lookup('template', 'Store.json.j2')}}"
    return_content: yes
    body_format: json
    status_code: 200
    validate_certs: no
    headers:
      content-type: "application/json"
      ReturnResultType: "FULL"
  register: resultStore

#-----------------------> Print error message for Failure case  <----------------------------

- fail:
    msg: "Instance creation failed with error code {{ result.content | regex_search('errorCode=[^ ]+') | replace('\"','') |replace('errorCode=','') }} and error message {{ result.content | regex_search('<errorMessage>.*</errorMessage>') | replace('<errorMessage>','') |replace('</errorMessage>','') }}"
  when: "target=='error'"