---
- name: Stop
  hosts: localhost
  # connection: local
  gather_facts: False
  pre_tasks:
    - name: setting filename
      set_fact:
        listrequestedServices: "{{ requestedServices.split(',') | map('trim') |  list }}"
    - name: setting filename
      set_fact:
        length_requestedServices: "{{  listrequestedServices | reject('search','VOICEMAIL') | list | length | int }}"
  tasks:
    - name: Conditional role
      include_role:
        name: ../roles/provide_addon
      when: "operation.find('PROVIDE') != -1 and length_requestedServices | int >= 1 "
    - name: Conditional role
      include_role:
        name: ../roles/cease_addon
      when: "operation.find('CEASE') != -1 and length_requestedServices | int >= 1 "
    - name: Conditional role
      include_role:
        name: ../roles/suspend
      when: "operation == 'Suspend' and 'VOICE' in listrequestedServices"
    - name: Conditional role
      include_role:
        name: ../roles/resume
      when: "operation == 'Resume' and 'VOICE' in listrequestedServices"         
  # roles:
  #   - { role: ../roles/provide_addon, when: "operation.find('PROVIDE') != -1 and length_requestedServices | int >= 1 " }
  #   - { role: ../roles/cease_addon, when: "operation.find('CEASE') != -1 and length_requestedServices | int >= 1 " }
  #   - { role: ../roles/suspend, when: "operation == 'Suspend' and 'VOICE' in listrequestedServices" }
  #   - { role: ../roles/resume, when: "operation == 'Resume' and 'VOICE' in listrequestedServices" }
  #   - { role: ../roles/ChangeDevice, when: operation == 'ChangeDevice' }
    # - 
    #   role: ../roles/ceasetas
    #   when: "operation == 'CleanupMsisdn,ChangeMsisdn'"
    # - 
    #   role: ../roles/ceaseenum
    #   when: "operation == 'CleanupMsisdn,ChangeMsisdn'"
    # - 
    #   role: ../roles/createenum
    #   when: "operation == 'CleanupMsisdn,ChangeMsisdn'"
    # - 
    #   role: ../roles/createtas
    #   when: "operation == 'CleanupMsisdn,ChangeMsisdn'"
    # - 
    #   role: ../roles/changevoicemail
    #   when: "operation == 'CleanupMsisdn,ChangeMsisdn'"

