---
- name: addSliceConfigProd
  hosts: amf
  gather_facts: False
  # roles:
  #   - role: ../roles/addSliceConfigProd
  tasks:
    - ping:
      register: ping_result
      ignore_unreachable: true

    - name: "testing"
      fail:
        msg: "server not reachable please check ip and password"
      when: ping_result.unreachable is defined 
        
# - name: run the Togglestub yaml file
#   import_playbook: addSliceConfigProd.yaml
#   when: lookup('env','AMF_ENV') == 'prod'
      
# - name: run the ToggleProd yaml file
#   import_playbook: addSliceConfigStub.yaml
#   when: lookup('env','AMF_ENV') == 'stub'

- name: run the Togglestub yaml file
  import_playbook: addSliceConfigProd.yaml
  when: AMF_ENV == 'prod'
      
- name: run the ToggleProd yaml file
  import_playbook: addSliceConfigStub.yaml
  when: AMF_ENV == 'stub'

    
