- name: Delete snssaiToDnnList and Insert a line at the end of a file.
  raw: cmm snssaiToDnnList delete --name {{ item }}
  register: result
  failed_when: "result.rc not in [0,1]"
#  ignore_errors: yes

- name: Insert a line to add deleted snssaiToDnnList in the end of a file.
  connection: local
  lineinfile:
    path: "{{ filename }}"
    line: |
          input: cmm snssaiToDnnList delete --name {{ item }}
          output: {{ result.stdout }}
  delegate_to: 127.0.0.1

#- fail:
#    msg: "{{ result.stdout | regex_search('ERROR.*') }}"
#  when:
#    - '"The relevant data content already exists" not in result.stdout'
#    - '"Field" not in result.stdout'
