#-------------------> update pLMNInfoList for EACH NRCellDU (Delete existing slice) <----------------
- name: update pLMNInfoList for EACH NRCellDU with new S-NSSAI (Delete existing slice)
  uri:
    url:  "{{ deployment_location.properties.mcms_host }}/cms-service/webapi/apiservice/ProvMnS/v1/data=1,ManagedElement=1,GNBDUFunction={{ du_id }},NRCellDU={{ NRCellDUidcease }},attributes/pLMNInfoList={{ du_mcc }}"
    method: DELETE
    body: "{{lookup('template', 'modifyInfoDU3GPP.json.j2')}}"
    # body: 
      # "gnbId": {{ gnb_id  | int }}
      # "cnfId": {{ du_id | int }}
      # "version": "{{ du_version }}"
      # "configType": "{{ du_3gpp_config }}"
    body_format: json
    headers:
      apiInvokerId: "{{ deployment_location.properties.apiInvokerId }}"
      content-type: "application/json"
      ReturnResultType: "FULL"
      return_content: yes
    validate_certs: no
    status_code: [200,500]
    return_content: yes
  register: cease_updatepLMNInfoList
  # loop: "{{ mysequenceNRCellDUcease }}"
  ignore_errors: yes
  failed_when: "cease_updatepLMNInfoList.status not in [200,500]"

# - name: Delete cease_updatepLMNInfoList print
  # copy:
    # dest: "/tmp/ansible_log/resp_ceaseDU3gppUpdatepLMNInfoList.json.j2"
    # content: "{{ cease_updatepLMNInfoList }}"

- name: Insert a line at the end of a file to print cease_updatepLMNInfoList.
  lineinfile:
    path: "{{ filen }}"
    line: |
           __________________________________________________________________________
           
           ##### DELETE API call to delete pLMNInfoList for EACH NRCellDU with new S-NSSAI (delete new slice)
           
           URL:  
           {{ cease_updatepLMNInfoList.url }}
           
           order_send:
           {{lookup('template', 'modifyInfoDU3GPP.json.j2')}}
           
           result_return: 
           {{ cease_updatepLMNInfoList.json | to_nice_json }}
           __________________________________________________________________________

- name: Log API request through Log module
  ibm_cp4na_log_message:
    message_direction: sent
    # external_request_id: "{{ extOrderId }}"
    external_request_id: "{{ kami_responseDUdel.json.extOrderId }}"
    content_type: application/json
    message_data: |
     ***********************************
     ##### DELETE API call to delete pLMNInfoList for EACH NRCellDU with new S-NSSAI (delete new slice)
     
     URL:  
     {{ cease_updatepLMNInfoList.url }}
     
     order_send:
     {{lookup('template', 'modifyInfoDU3GPP.json.j2')}}
     ____________________________________________________

     result_return:
      {{ cease_updatepLMNInfoList.json | to_nice_json }}
    message_type: sample
    protocol: http

#-----------------> Print error message when apiInvokerId is Invalid/incorrect/expired <------------
- name: creating variable and setting value for message error when apiInvokerId is Invalid/incorrect/expired
  set_fact:
    target_e: "{{ cease_updatepLMNInfoList.content | regex_search('message') }}"

- fail:
    msg: "Instance creation failed with error {{ cease_updatepLMNInfoList.content | replace('\"','') | replace('{','') | replace('}','') }}. Either apiInvokerId is Invalid/incorrect/expired, please verify the apiInvokerId."
  when: "target_e=='message'"

#-----------> Print cease_updatepLMNInfoList error message if Add/Delete API calls fails <---------------
# - name: creating variable and setting value for errorInfo  
  # set_fact:
    # target_e1: "{{ cease_updatepLMNInfoList.content | regex_search('error') }}"

# - fail:
    # msg: "Instance creation failed with error {{ cease_updatepLMNInfoList.content | replace('\"','') | replace('{','') | replace('}','') | replace('error:','') }}"
  # when: "target_e1=='error'"    