# convert ALM properties to json provide request for South Bound endpoint - Nokia Provisioning GW
- name: Creates directory
  file:
    path: /tmp/ansible_log
    state: directory
    mode: 0775

- name: setting filename
  set_fact:
    filename: /tmp/ansible_log/ansible_{{ extOrderId }}_{{ ansible_date_time.iso8601 }}.log
- shell: "python3 test.py"
  register: start_time
  no_log: True


- name: Call RestAPI of SPML Adapter
  uri:
    url: "{{ ansible_env.VOICEMAIL_ADAP_HOST }}/dish/ProvVoicemail/voice/provide/VoiceMail"
    method: POST
    body: "{{lookup('template', 'nokia_provisioning_gw_voicemail_provide_request.json.j2')}}"
    status_code: 200
    body_format: json
    headers: 
      content-type: "application/json"
      Returnresult_VoicemailProvideType: "FULL"
      return_content: yes      
  register: result_VoicemailProvide
  ignore_errors: yes
  
- name: Check that url returns a status_code 200 and fail if status_code 200 is not returns
  fail:
    msg: Instance creation failed with error code {{ result_VoicemailProvide.status }} and error message {{ result_VoicemailProvide.json.error.message }}
  when:  result_VoicemailProvide.status!=200 and result_VoicemailProvide.json is defined

- name: Check that url returns a status_code 200 and fail if status_code 200 is not returns
  fail:
    msg: Instance creation failed with error code {{ result_VoicemailProvide.status }} and error message {{ result_VoicemailProvide.msg }}
  when: result_VoicemailProvide.status != 200
  
  
- shell: "python3 test.py"
  register: end_time
  no_log: True

- shell: "python3 diff.py '{{ end_time.stdout }}' '{{ start_time.stdout }}'"
  register: time_diff
  no_log: True

- name: generate SB json and copy       
  copy:
    dest: "{{ filename }}"
    content: |
       ***********************************
       start_time:  {{ start_time.stdout }}
       end_time:  {{ end_time.stdout }}
       time_taken:  {{ time_diff.stdout }}
       ***********************************
       order_send:  {{lookup('template', 'nokia_provisioning_gw_voicemail_provide_request.json.j2')}}
       ____________________________________________________
       result_VoicemailProvide_return: {{ result_VoicemailProvide.json }}  
                  

- name: fail instance if there is a failure from SBI
  fail:
   msg: Instance creation failed with error code {{ result_VoicemailProvide.json.output.errorCode }} and error message {{ result_VoicemailProvide.json.output.message }}
  when: result_VoicemailProvide.json.output.result == "Failure"