---
- name: Install
  hosts: localhost
  connection: local
  gather_facts: False
  roles: 
   - { role: ../roles/NOIProd }
   # - { role: ../roles/NOIProd/tasks/NOIStub.yml, when: ansible_env.NOI_ENV == 'Stub' }
   # - { role: ../roles/BPIStub, when: ansible_env.BPI_ENV == 'stub' }
   # - { role: ../roles/BPIProd, when: ansible_env.BPI_ENV == 'prod' }