#----------------------->Set Enum url    <----------------------------
- name: "##ALM## setting Enum url"
  set_fact:
    enum_provide_url: "{{ deployment_location.properties.enum_provide_url2 }}"



#-----------------------> SOAP call for ENUM Provide operation for Secondary URL <----------------------------
- name: "##ENUM##Call Soap of SPML Adapter for Secondary location"
  environment:
    SSL_CERT_FILE: "pgwcertificate.cert"
  uri:
    url: "{{ enum_provide_url }}"
    method: POST
    body: "{{lookup('template', 'nokia_enum_provide.xml.j2')}}"
    return_content: yes
    #status_code: [200,201]
    headers:
      content-type: "text/xml"
      ReturnResultType: "FULL"
      return_content: yes
  register: result
  until: result.status == 200
  retries: "{{ RETRY_COUNT }}"
  delay: "{{ RETRY_INTERVAL }}"