---
# - hosts: localhost
#   connection: local
#   gather_facts: true
#   tasks:
#     - name: seting variable
#       set_fact:
#         AMF_ENV: "{{ ansible_env.AMF_ENV }}"    
        
# - name: run the Togglestub yaml file
#   import_playbook: addSliceConfigProd.yaml
#   when: lookup('env','AMF_ENV') == 'prod'
      
# - name: run the ToggleProd yaml file
#   import_playbook: addSliceConfigStub.yaml
#   when: lookup('env','AMF_ENV') == 'stub'

- name: run the Togglestub yaml file
  import_playbook: addSliceConfigProd.yaml
  when: AMF_ENV == 'prod'
      
- name: run the ToggleProd yaml file
  import_playbook: addSliceConfigStub.yaml
  when: AMF_ENV == 'stub'

    
