---
# - hosts: localhost
#   connection: local
#   gather_facts: true
#   tasks:
#     - name: seting variable
#       set_fact:
#         AMF_ENV: "{{ ansible_env.AMF_ENV }}" 

# - name: run the removeSliceProd yaml file
#   import_playbook: removeSliceProd.yaml
#   when: lookup('env','AMF_ENV') == 'prod'
      

# - name: run the removeSliceStub yaml file
#   import_playbook: removeSliceStub.yaml
#   when: lookup('env','AMF_ENV') == 'stub'

- name: run the removeSliceProd yaml file
  import_playbook: removeSliceProd.yaml
  when:  AMF_ENV  == 'prod'
      

- name: run the removeSliceStub yaml file
  import_playbook: removeSliceStub.yaml
  when:  AMF_ENV  == 'stub'
