---
- name: Unistall
  hosts: localhost
  connection: local
  gather_facts: True
  pre_tasks:
    - set_fact:
        listrequestedServices: "{{ requestedServices.split(',') | map('trim') |  list }}"
  roles:
      - { role: ../roles/cease, when: "'VOICEMAIL' in listrequestedServices" }