#-----------------------> Set pgw url    <----------------------------
- name: "##ALM## setting pgw url"
  set_fact:
    pgw_url: "{{ deployment_location.properties.pgw_url2 }}"


#-----------------------> PGW API call for cease with secondary URL  <----------------------------
- name: "##PGW## call Soap of SPML Adapter"
  environment:
    SSL_CERT_FILE: "pgwcertificate.cert"
  uri:
    url: "{{ pgw_url }}"
    method: POST
    validate_certs: no
    return_content: yes
    body: "{{lookup('template', 'bundle_cease.xml.j2')}}"
    #status_code: [200,201]
    # retry_count: "{{ ansible_env.RETRY_COUNT }}"
    # retry_interval: "{{ ansible_env.RETRY_INTERVAL }}"
    headers:
      content-type: "text/xml"
      ReturnResultType: "FULL"
      return_content: yes
      SOAPAction: ""
  register: result
  until: result.status == 200
  retries: "{{ RETRY_COUNT }}"
  delay: "{{ RETRY_INTERVAL }}"