# Send Command to South Bound endpoint - Nokia SMF
- name: Create the list
  set_fact:   
    list_smf_dnnName: "{{ smf_dnnName.split(',')| map('trim')| list }}" 

- name: generate SB json and copy it to utility server
  copy:
    dest: "smf.sh"
    content: |
      #!/usr/bin/expect
      spawn ssh admin@10.223.128.243 -p 2222
      expect "password: "
      send "admin\r"
      expect eof 

- name: Insert a line at the end of a file.
  lineinfile:
    path: "smf.sh"
    line: |
            send "configure mobile-gateway profile list slice-instance-list {{ smfSlice_sliceInstanceListName }}\r" 
            send "exit\r"
            send "configure mobile-gateway profile list slice-instance-list {{ smfSlice_sliceInstanceListName }} slice-instance {{ smfSlice_slice_instance  }}\r"
            send "configure mobile-gateway profile list slice-list {{ smfSlice_sliceListName }} slice {{ smfSlice_sliceName }} sst {{ smfSlice_sst }} sd {{ smfSlice_sd }} slice-instances {{ smfSlice_slice_instance }}\r"
            send "configure mobile-gateway pdn 5 instance-type user\r"
            send "configure mobile-gateway pdn 5 slices slice-list {{ smfSlice_sliceListName }}\r"
            send "configure mobile-gateway pdn 5 slices slice-instance-list {{ smfSlice_sliceInstanceListName }}\r"

- name: Insert a line at the end of a file.
  lineinfile:
    path: "smf.sh"
    line: send "configure mobile-gateway pdn 5 apn {{ item }} slices slice-list {{ smfSlice_sliceListName }}\r"
  loop: "{{ list_smf_dnnName }}"

- name: Insert a line at the end of a file.
  lineinfile:
    path: "smf_{{ instance_name }}.sh"
    line: send "exit all\r"

- name: Insert a line at the end of a file.
  lineinfile:
    path: "smf_{{ instance_name }}.sh"
    line: expect eof

- name: running script
  command: chmod 775 smf_{{ instance_name }}.sh
- name: running script
  command: ./smf_{{ instance_name }}.sh
  register: result

- debug: var=result
