---
- name: Install
  hosts: localhost
  # connection: local
  gather_facts: False
  pre_tasks:
    - set_fact:
        listrequestedServices: "{{ requestedServices.split(',') | map('trim') |  list }}"
  tasks:
    - name: Conditional role
      include_role:
        name: ../roles/provide
      when: "'VOICEMAIL' in listrequestedServices and ( loop_back == 'OFF' or loop_back == 'false')"
  # roles:
  #     - { role: ../roles/provide, when: "'VOICEMAIL' in listrequestedServices and ( loop_back == 'OFF' or loop_back == 'false')" }
