- name: Creates directory
  file:
    path: /tmp/ansible_log
    state: directory
    mode: 0775

- name: setting filename
  set_fact:
    filename: /tmp/ansible_log/ansible_{{ extOrderId }}_{{ ansible_date_time.iso8601 }}.log
- shell: "python3 test.py"
  register: start_time
  no_log: True  


  
# - name: generate Ub SB json and copy it to utility server
#   template:
#     src: nokia_provisioning_gw_unblock_sim_provide_request.json.j2
#     dest: /tmp/nokia_provisioning_gw_unblock_sim_request_{{ instance_name }}.json


- name: Call RestAPI of SPML Adapter ubl
  uri:
    url:  "{{ ansible_env.PGW_ADA_HOST }}/dish/ProvSpml/api/v1/spmlAdapter/modifyAddRequest"
    method: POST
    body: "{{lookup('template', 'nokia_provisioning_gw_unblock_sim_provide_request.json.j2')}}"
    status_code: 200
    body_format: json
    headers:
      content-type: "application/json"
      Returnresult_UnblockSIMType: "FULL"
  register: result_UnblockSIM
  ignore_errors: yes
  
- name: Check that url returns a status_code 200 and fail if status_code 200 is not returns
  fail:
    msg: Instance creation failed with error code {{ result_UnblockSIM.status }} and error message {{ result_UnblockSIM.json.error.error_message }}
  when:  result_UnblockSIM.status!=200 and result_UnblockSIM.json is defined

- name: Check that url returns a status_code 200 and fail if status_code 200 is not returns
  fail:
    msg: Instance creation failed with error code {{ result_UnblockSIM.status }} and error message {{ result_UnblockSIM.msg }}
  when: result_UnblockSIM.status != 200

- shell: "python3 test.py"
  register: end_time
  no_log: True

- shell: "python3 diff.py '{{ end_time.stdout }}' '{{ start_time.stdout }}'"
  register: time_diff
  no_log: True

- name: generate SB json and copy       
  copy:
    dest: "{{ filename }}"
    content: |
       ***********************************
       start_time:  {{ start_time.stdout }}
       end_time:  {{ end_time.stdout }}
       time_taken:  {{ time_diff.stdout }}
       ***********************************
       order_send:  {{lookup('template', 'nokia_provisioning_gw_unblock_sim_provide_request.json.j2')}}
       ____________________________________________________
       result_UnblockSIM_return: {{ result_UnblockSIM.json }}   
  
- name: fail instance if there is a failure from SBI
  fail:
    msg: Instance creation failed with error code {{ result_UnblockSIM.json.output.errorcode }} and error message {{ result_UnblockSIM.json.output.message }}
  when: result_UnblockSIM.json.output.result == "Failure"

