---
# - hosts: localhost
#   connection: local
#   gather_facts: true
#   tasks:
#     - name: seting variable
#       set_fact:
#         SMF_ENV: "{{ ansible_env.SMF_ENV }}"

# - name: run the removeSliceProd yaml file
#   import_playbook: removeSliceProd.yaml
#   when: lookup('env','SMF_ENV') == 'prod'
      
# - name: run the removeSliceStub yaml file
#   import_playbook: removeSliceStub.yaml
#   when: lookup('env','SMF_ENV') == 'stub'

- name: run the removeSliceProd yaml file
  import_playbook: removeSliceProd.yaml
  when:  SMF_ENV  == 'prod'
      
- name: run the removeSliceStub yaml file
  import_playbook: removeSliceStub.yaml
  when:  SMF_ENV  == 'stub'
