# convert ALM properties to json provide request for South Bound endpoint - Nokia Provisioning GW 
- name: Creates directory
  file:
    path: /tmp/ansible_log
    state: directory
    mode: 0775

- name: setting filename
  set_fact:
    filename: /tmp/ansible_log/ansible_{{ extOrderId }}_{{ ansible_date_time.iso8601 }}.log
- shell: "python3 test.py"
  register: start_time
  no_log: True 
   
- name: Call RestAPI of SPML/TAS/ENUM Adapter
  uri:
    url:  "{{ ansible_env.TAS_ENUM_ADA_HOST }}/dish/Prov/tas/addRequest"
    method: POST
    body: "{{lookup('template', 'nokia_provisioning_gw_tas_provide_request.json.j2')}}"
    status_code: 200
    body_format: json
    headers:
      content-type: "application/json"
      Returnresult_VoicePGWTasType: "FULL"
    return_content: yes
  register: result_VoicePGWTas
  ignore_errors: yes
  
- name: Check that url returns a status_code 200 and fail if status_code 200 is not returns
  fail:
    msg: Instance creation failed with error code {{ result_VoicePGWTas.status }} and error message {{ result_VoicePGWTas.json.error.message }}
  when:  result_VoicePGWTas.status!=200 and result_VoicePGWTas.json is defined

- name: Check that url returns a status_code 200 and fail if status_code 200 is not returns
  fail:
    msg: Instance creation failed with error code {{ result_VoicePGWTas.status }} and error message {{ result_VoicePGWTas.msg }}
  when: result_VoicePGWTas.status != 200

  
- shell: "python3 test.py"
  register: end_time
  no_log: True

- shell: "python3 diff.py '{{ end_time.stdout }}' '{{ start_time.stdout }}'"
  register: time_diff
  no_log: True

- name: generate SB json and copy       
  lineinfile:
    path: "{{ filename }}"
    line: |
       ***********************************
       start_time:  {{ start_time.stdout }}
       end_time:  {{ end_time.stdout }}
       time_taken:  {{ time_diff.stdout }}
       ***********************************
       order_send:  {{lookup('template', 'nokia_provisioning_gw_tas_provide_request.json.j2')}}
       ____________________________________________________
       result_VoicePGWTas_return: {{ result_VoicePGWTas.json }}  
      

- name: fail instance if there is a failure from SBI
  fail:
    msg: Instance creation failed with error code {{ result_VoicePGWTas.json.output.errorCode }} and error message {{ result_VoicePGWTas.json.output.message }}
  when: result_VoicePGWTas.json.output.result == "Failure"

