---
- name: Stop
  hosts: localhost
  connection: local
  gather_facts: True
  roles:
    - { role: ../roles/suspend, when: operation == 'Suspend' }
    - { role: ../roles/resume, when: operation == 'Resume' }
    - { role: ../roles/ChangeDevice, when: operation == 'ChangeDevice' }
    - 
      role: ../roles/ceasetas
      when: "operation == 'CleanupMsisdn,ChangeMsisdn'"
    - 
      role: ../roles/ceaseenum
      when: "operation == 'CleanupMsisdn,ChangeMsisdn'"
    - 
      role: ../roles/createenum
      when: "operation == 'CleanupMsisdn,ChangeMsisdn'"
    - 
      role: ../roles/createtas
      when: "operation == 'CleanupMsisdn,ChangeMsisdn'"
    - 
      role: ../roles/changevoicemail
      when: "operation == 'CleanupMsisdn,ChangeMsisdn'"

