---
- name: addSliceConfigProd
  hosts: amf
  gather_facts: False
  # roles:
  #   - role: ../roles/addSliceConfigProd
  tasks:
    - ping:
      register: ping_result
      ignore_unreachable: true

    - name: "testing"
      fail:
        msg: "please make sure all server up and run again"
      when: ping_result.unreachable is defined
      any_errors_fatal: true
    - include_role:
        name: ../roles/addSliceConfigProd
      when: "ping_result.unreachable is not defined"   