- name: Copy Shell Script to Anisble Host.
  template:
    src: noi-consumer_request_AIOPS.sh
    dest: /tmp/noi-consumer_request_AIOPS.sh

- name: Make script executable
  command: chmod +x /tmp/noi-consumer_request_AIOPS.sh

- script: /tmp/noi-consumer_request_AIOPS.sh "{{ amf_assembly_name }}"
  register: result

- debug: var=result.stdout_lines

- name: NE_Not_Available
  fail:
    msg: NE Not Available amf failed 
  when: result.stdout_lines[0] == "NE_Not_Available"


- script: /tmp/noi-consumer_request_AIOPS.sh "{{ smf_assembly_name }}"
  register: result

- debug: var=result.stdout_lines

- name: NE_Not_Available
  fail:
    msg: NE Not Available smf failed 
  when: result.stdout_lines[0] == "NE_Not_Available"