#-------------------> update rRMPolicyMemberList for EACH NRCellDU with new slice <----------------
- name: update rRMPolicyMemberList for each NRCellDU(add new slice)
  uri:
    url: "{{ deployment_location.properties.mcms_host }}/cms-service/webapi/apiservice/ProvMnS/v1/data=1,ManagedElement=1,GNBDUFunction={{ du_id }},NRCellDU={{ NRCellDURRMid }},attributes/rRMPolicyMemberList"
    method: PUT
    body: "{{lookup('template', 'modifyrRMPolicyMemberListDU3GPP.json.j2')}}"
    body_format: json
    headers:
      apiInvokerId: "{{ deployment_location.properties.apiInvokerId }}"
      content-type: "application/json"
      ReturnResultType: "FULL"
      return_content: yes
    validate_certs: no
    status_code: 201
    return_content: yes
  register: updaterRMPolicyMemberList
  # loop: "{{ mysequenceNRCellDURRM }}"
  ignore_errors: yes
  failed_when: "updaterRMPolicyMemberList.status not in [201]"

# - name: updaterRMPolicyMemberList print
  # copy:
    # dest: "/tmp/ansible_log/proDU3gppupdaterRMPolicyMemberList.json.j2"
    # content: "{{ updaterRMPolicyMemberList }}"

- name: Insert a line at the end of a file to update print updaterRMPolicyMemberList.
  lineinfile:
    path: "{{ filen }}"
    line: |
           __________________________________________________________________________
           
           ##### PUT API call to update rRMPolicyMemberList for each NRCellDU(add new slice)
           
           URL:  
           {{ updaterRMPolicyMemberList.url }}
           
           order_send:
           {{lookup('template', 'modifyrRMPolicyMemberListDU3GPP.json.j2')}}
           
           result_return: 
           {{ updaterRMPolicyMemberList.json | to_nice_json }}
           __________________________________________________________________________

- name: Log API request through Log module
  ibm_cp4na_log_message:
    message_direction: sent
    external_request_id: "{{ extOrderId }}"
    content_type: application/json
    message_data: |
     ***********************************
     ##### PUT API call to update rRMPolicyMemberList for each NRCellDU(add new slice)
     
     URL:  
     {{ updaterRMPolicyMemberList.url }}
     
     order_send:
     {{lookup('template', 'modifyrRMPolicyMemberListDU3GPP.json.j2')}}
     ____________________________________________________

     result_return:
      {{ updaterRMPolicyMemberList.json | to_nice_json }}
    message_type: sample
    protocol: http

#-----------------> Print error message when apiInvokerId is Invalid/incorrect/expired <------------
- name: creating variable and setting value for message error when apiInvokerId is Invalid/incorrect/expired
  set_fact:
    target_e: "{{ updaterRMPolicyMemberList.content | regex_search('message') }}"

- fail:
    msg: "Instance creation failed with error {{ updaterRMPolicyMemberList.content | replace('\"','') | replace('{','') | replace('}','') }}. Either apiInvokerId is Invalid/incorrect/expired, please verify the apiInvokerId."
  when: "target_e=='message'"

#-----------> Print updaterRMPolicyMemberList error message if Add/Delete API calls fails <---------------
- name: creating variable and setting value for errorInfo  
  set_fact:
    target_e1: "{{ updaterRMPolicyMemberList.content | regex_search('error') }}"

- fail:
    msg: "Instance creation failed with error {{ updaterRMPolicyMemberList.content | replace('\"','') | replace('{','') | replace('}','') | replace('error:','') }}"
  when: "target_e1=='error'"