# convert ALM properties to json provide request for South Bound endpoint - Nokia Provisioning GW 
- name: Create the list
  set_fact:   
    list_amfTac: "{{ amfSlice_tai.split(',') | list }}" 
    list_amfSlice_dnnName: "{{ amfSlice_dnnName.split(',') | list }}" 
        

- name: generate SB json and copy       
  copy:
    dest: "/tmp/AMF_PROVIDE_{{ instance_name }}.sh"
    content: |
      # 

- name: Insert a line at the end of a file.
  lineinfile:
    path: "/tmp/AMF_PROVIDE_{{ instance_name }}.sh"
    line: 
      cmm amfTai create --plmnName {{ amfSlice_plmnName }} --amfTac {{ item }}  --timeZoneName {{ amfSlice_timeZone}}
  loop: "{{ list_amfTac }}"

- name: Insert a line at the end of a file.
  lineinfile:
    path: "/tmp/AMF_PROVIDE_{{ instance_name }}.sh"
    line: |
      cmm snssaiList create --name {{ amfSlice_snssaiListName }}
      cmm snssai create --name {{ amfSlice_sliceName }} --sliceServiceType {{ amfSlice_sst }} --sliceDifferentiator {{ amfSlice_sd | upper }} --supportedInAllTa {{ amfSlice_supportedInAllTacFlag }}
      cmm snssaiListItem create --snssaiListName {{ amfSlice_snssaiListName}} --snssaiName {{ amfSlice_sliceName }} 
      cmm amfSetSnssai create --plmnName {{ amfSlice_plmnName }} --amfRegionId {{ amfSlice_amfRegionId}} --amfSetId {{ amfSlice_amfSetId }} --snssaiListName {{ amfSlice_snssaiListName }}
      cmm snssaiToDnnList create --name {{ amfSlice_snssaiToDnnListName }}

- name: Insert a line at the end of a file.
  lineinfile:
    path: "/tmp/AMF_PROVIDE_{{ instance_name }}.sh"
    line: cmm snssaiToDnn create --dataNetworkName {{ item }} --snssaiToDnnListName {{ amfSlice_snssaiToDnnListName}} --snssaiName {{ amfSlice_sliceName }}
  loop: "{{ list_amfSlice_dnnName }}"


- name: Insert a line at the end of a file.
  lineinfile:
    path: "/tmp/AMF_PROVIDE_{{ instance_name }}.sh"
    line: cmm amfUePlmnServices modify {{ amfSlice_plmnName }} --defaultSnssaiSelection {{ amfSlice_defaultSnssaiSelection }} --defaultSnssaiListName {{ amfSlice_snssaiListName }} --snssaiToDnnListName {{ amfSlice_snssaiToDnnListName }}