---        
# - name: run the Togglestub yaml file
#   import_playbook: addSliceConfigProd.yaml
#   when: lookup('env','NSSF_ENV') == 'prod'
      
# - name: run the ToggleProd yaml file
#   import_playbook: addSliceConfigStub.yaml
#   when: lookup('env','NSSF_ENV') == 'stub'

- name: run the Togglestub yaml file
  import_playbook: addSliceConfigProd.yaml
  when: NSSF_ENV  == 'prod'
      
- name: run the ToggleProd yaml file
  import_playbook: addSliceConfigStub.yaml
  when: NSSF_ENV == 'stub'



    
