---
# - name: run the removeSliceProd yaml file
#   import_playbook: removeSliceProd.yaml
#   when: lookup('env','NSSF_ENV') == 'prod'
      

# - name: run the removeSliceStub yaml file
#   import_playbook: removeSliceStub.yaml
#   when: lookup('env','NSSF_ENV') == 'stub'

- name: run the removeSliceProd yaml file
  import_playbook: removeSliceProd.yaml
  when: NSSF_ENV  == 'prod'
      

- name: run the removeSliceStub yaml file
  import_playbook: removeSliceStub.yaml
  when: NSSF_ENV  == 'stub'


