- name: Create PCCrule Data
  uri:
    url: "{{ PCF_HOST }}/oc-cnpolicy-configuration/v1/policydata/pcfsm/pccrules"
    method: POST
    body: "{{lookup('template', '/tmp/{{ pccrules }}_pcc_rule.json.j2')}}"
    status_code: [201,400,401]
    body_format: json
    headers:
      content-type: "application/json"
      cache-control: "no-cache"
    return_content: yes
  #loop: "{{ list_pcf_qosData_Id }}"
  register: PCCrule

- debug: msg="{{ PCCrule.status }}"
- set_fact:
    loopback: "true"
    fail_content: "{{ PCCrule.content }}"
  when: "PCCrule.status == 400"

- name: Insert a line at the end of a file.

  lineinfile:

    path: "{{ filen }}"

    line: |
           order_send:  {{lookup('template', '/tmp/{{ pccrules }}_pcc_rule.json.j2')}}
           __________________________________________________________________________
           
           result_return: {{ PCCrule }}
           
           __________________________________________________________________________