- name: Create QoS Data
  uri:
    url: "{{ PCF_HOST }}/oc-cnpolicy-configuration/v1/policydata/pcfsm/qosinformation"
    method: POST
    body: "{{lookup('template', '/tmp/{{ qosinfo }}_Qos_info.json.j2')}}"
    status_code: [201,400,401]
    body_format: json
    headers:
      content-type: "application/json"
      cache-control: "no-cache"
    return_content: yes
  #loop: "{{ list_pcf_qosData_Id }}"
  register: QOSinfo

- debug: msg="{{ QOSinfo.status }}"
- set_fact:
    loopback: "true"
    fail_content: "{{ QOSinfo.content }}"
  when: "QOSinfo.status == 400"

- name: Insert a line at the end of a file.

  lineinfile:

    path: "{{ filen }}"

    line: |
           order_send:  {{lookup('template', '/tmp/{{ qosinfo }}_Qos_info.json.j2')}}
           __________________________________________________________________________
           
           result_return: {{ QOSinfo }}