---
- name: Reconfigure
  hosts: localhost
  connection: local
  gather_facts: False
  # roles:
  #   - { role: ../roles/suspend, when: operation == 'Suspend' }
  #   - { role: ../roles/resume, when: operation == 'Resume' }
  #   - { role: ../roles/BlockSIM, when: operation == 'BlockSIM' }
  #   - { role: ../roles/UnblockSIM, when: operation == 'UnblockSIM' }
  #   - { role: ../roles/ChangeSIM, when: operation == 'ChangeSIM' }
  #   - { role: ../roles/ChangeDevice, when: operation == 'ChangeDevice' }
