#####name: Call when Slice ID XPath is not present (Create First slice-Index with value 0)
#####include: CUUP_SliceID0.yaml

- name: Read xml data to calculate the slice-index
  xml:
    xmlstring: "{{ lookup('file', '{{ xmlfile }}') }}"
    namespaces:
      ns: http://www.samsung.com/global/business/5GvRAN/ns/gnb-cu-up-cnf
    xpath: /data/ns:managed-element/ns:gnb-cu-up-function/ns:gnb-cu-up-slice-info/ns:slice-index
    content: 'text'
  register: xml_result

- name: Print slice-index matches
  debug:
    var: xml_result.matches

##find length of Arrray of dict(json)
- name: Print the length of SliceIndex
  set_fact:
    # sliceIndex: "{{ xml_result.matches | length }}"
    sliceIndex: "{{ xml_result.matches | length | default(0) }}"

##Extract last entry from array in dict(json) format
- name: Print First SliceIndex(Id=0) entry from array in json(dict) format (key:value pair)
  set_fact:
    SliceIdZero: "{{ xml_result.matches[0] }}"

## Extract only key from last SliceIndex entry of array
- name: Print only key from last SliceIndex entry
  set_fact:
    SliceIdZeroKeyonly: "{{ SliceIdZero.keys() }}"

## Extract First key from dict of keys
- name: Print first key from last SliceIndex entry if found multiple
  set_fact:
    SliceIdFirstKey: "{{ SliceIdZeroKeyonly[0] }}"

- debug:
    msg: "{{ SliceIdFirstKey }}"

- name: Print slice-Index value of the last entry in list
  set_fact:
    sliceIndexZeroKeyvalue: "{{ SliceIdZero[SliceIdFirstKey] }}"

- name: Print sliceIndexZeroKeyvalue
  debug:
    msg: "{{ sliceIndexZeroKeyvalue }}"

#----------------> CU_UP Slice delete slice  <--------------
- name: Call RestAPI to Delete CU_UP for Slice Index =0 
  uri:
    url: "{{ cuup_samsung_usm_host }}/oss/netconf/AUPF_25155100"
    # user: ossuser
    # password: osspasswd
    method: POST
    body: "{{lookup('template', 'delete_slice_CUUP_Sliceindex0.xml')}}"
    # body_format: json
    headers:
      Authorization: Basic b3NzdXNlcjpvc3NwYXNzd2Q=
      content-type: "application/xml"
      ReturnResultType: "FULL"
      return_content: yes
    validate_certs: no
    status_code: 200
    return_content: yes
  register: CU_UP_deleteSlice
  # ignore_errors: yes

- name: Display response
  debug:
    var: CU_UP_deleteSlice
    
- name: CU_UP_getSlice info print
  lineinfile:
    path: "{{ logsfile }}"
    line: |
           __________________________________________________________________________
           
           ##### Delete Slice for CUUP
           
           URL:  
           {{ CU_UP_deleteSlice.url }}
           
           order_send:
           {{lookup('template', 'delete_slice_CUUP_Sliceindex0.xml')}}
           
           result_return:
           {{ CU_UP_deleteSlice.content }}
           __________________________________________________________________________
