- name: Creates directory
  file:
    path: /tmp/ansible_log
    state: directory
    mode: 0775

- name: setting filename
  set_fact:
    filename: /tmp/ansible_log/ansible_{{ extOrderId }}_{{ ansible_date_time.iso8601 }}.log
    listrequestedServices: "{{ requestedServices.split(',') | map('trim') |  list }}"

- shell: "python3 test.py"
  register: start_time
  no_log: True

- name: Call RestAPI of SPML Adapter
  uri:
    url:  "{{ ansible_env.PGW_ADA_HOST }}/dish/ProvSpml/api/v1/spmlAdapter/resumeRequest"
    method: POST
    body: "{{lookup('template', 'nokia_provisioning_databundle_resume_request.json.j2')}}"
    body_format: json
#    timeout: 2
    headers:
      content-type: "application/json"
      ReturnResultType: "FULL"
  retries: "{{ ansible_env.RETRY_COUNT }}"
  delay: "{{ ansible_env.RETRY_INTERVAL }}" 
  register: result
  ignore_errors: yes

- name: Check that url returns a status_code 200 and fail if status_code 200 is not returns
  fail:
    msg: Instance creation failed with error code {{ result.status }} and error message {{ result.json.error.message }}
  when:  result.status!=200 and result.json is defined

- name: Check that url returns a status_code 200 and fail if status_code 200 is not returns
  fail:
    msg: Instance creation failed with error code {{ result.status }} and error message {{ result.msg }}
  when: result.status != 200

- shell: "python3 test.py"
  register: end_time
  no_log: True

- shell: "python3 diff.py '{{ end_time.stdout }}' '{{ start_time.stdout }}'"
  register: time_diff
  no_log: True

- name: generate SB json and copy       
  copy:
    dest: "{{ filename }}"
    content: |
       ***********************************
       start_time:  {{ start_time.stdout }}
       end_time:  {{ end_time.stdout }}
       time_taken:  {{ time_diff.stdout }}
       ***********************************
       order_send:  {{lookup('template', 'nokia_provisioning_databundle_resume_request.json.j2')}}
       ____________________________________________________
       result_return: {{ result.json }}

- name: fail instance if there is a failure from SBI
  fail:
    msg: Instance creation failed with error code {{ result.json.output.errorcode }} and error message {{ result.json.output.message }}
  when: result.json.output.result == "Failure"
