#
- name: Create Session Rule
  uri:
    url:  "http://pcf-stub-alm.dish-roks-poc-f5ae0bb7881b3b49feaa20ca32bad577-0000.us-south.containers.appdomain.cloud:32191/oc-cnpolicyconfiguration/v1/policydata/pcfsm/sessionrules"
    method: POST
    body: "{{lookup('template', 'oracle_provisioning_session_rule_request.json.j2')}}"
    status_code: 200
    body_format: json
    headers:
      content-type: "application/json"
      cache-control: "no-cache"
    return_content: yes
  register: result

- name: fail instance if there is a failure from SBI
  fail:
    msg: Instance creation failed with error code {{ result.json.errorcode }} and error message {{ result.json.errormessage }}
  failed_when: result.json.result != "200"