- name: update rRMPolicyMemberList for each NRCellDU (Delete existing slice)
  uri:
    url: "{{ deployment_location.properties.mcms_host }}/cms-service/webapi/apiservice/ProvMnS/v1/data=1,ManagedElement=1,GNBDUFunction={{ du_id }},NRCellDU={{ NRCellDURRMidcease }},attributes/rRMPolicyMemberList={{ rRMDUidxDel[0].idx }}"
    method: DELETE
    body: "{{lookup('template', 'modifyInfoDU3GPP.json.j2')}}"
    # body: 
      # "gnbId": {{ gnb_id  | int }}
      # "cnfId": {{ du_id | int }}
      # "version": "{{ du_version }}"
      # "configType": "{{ du_3gpp_config }}"    
    body_format: json
    headers:
      apiInvokerId: "{{ deployment_location.properties.apiInvokerId }}"
      content-type: "application/json"
      ReturnResultType: "FULL"
      return_content: yes
    validate_certs: no
    status_code: 200
    return_content: yes    
  register: cease_updaterRMPolicyMemberList
  # loop: "{{ mysequenceNRCellDURRMcease }}"
  ignore_errors: yes
  failed_when: "cease_updaterRMPolicyMemberList.status not in [200]"

# - name: updaterRMPolicyMemberList print
  # copy:
    # dest: "/tmp/ansible_log/ceaseDU3gppupdaterRMPolicyMemberList.json.j2"
    # content: "{{ cease_updaterRMPolicyMemberList }}"

- name: Insert a line at the end of a file to update print updaterRMPolicyMemberList.
  lineinfile:
    path: "{{ filen }}"
    line: |
           __________________________________________________________________________
           
           ##### DELETE API call to delete rRMPolicyMemberList for each NRCellDU(delete new slice)
           
           URL:  
           {{ cease_updaterRMPolicyMemberList.url }}
           
           order_send:
           {{lookup('template', 'modifyInfoDU3GPP.json.j2')}}
           
           result_return: 
           {{ cease_updaterRMPolicyMemberList.json | to_nice_json }}
           __________________________________________________________________________

#-----------------> Print error message when apiInvokerId is Invalid/incorrect/expired <------------
- name: creating variable and setting value for message error when apiInvokerId is Invalid/incorrect/expired
  set_fact:
    target_e: "{{ cease_updaterRMPolicyMemberList.content | regex_search('message') }}"

- fail:
    msg: "Instance creation failed with error {{ cease_updaterRMPolicyMemberList.content | replace('\"','') | replace('{','') | replace('}','') }}. Either apiInvokerId is Invalid/incorrect/expired, please verify the apiInvokerId."
  when: "target_e=='message'"

#-----------> Print cease_updaterRMPolicyMemberList error message if Add/Delete API calls fails <---------------
- name: creating variable and setting value for errorInfo  
  set_fact:
    target_e1: "{{ cease_updaterRMPolicyMemberList.content | regex_search('error') }}"

- fail:
    msg: "Instance creation failed with error {{ cease_updaterRMPolicyMemberList.content | replace('\"','') | replace('{','') | replace('}','') | replace('error:','') }}"
  when: "target_e1=='error'"