# convert ALM properties to json cease request for South Bound endpoint - Nokia Provisioning GW
- name: Get ALM Token
  uri:
    method: POST
    url: https://ishtar:8280/oauth/token?grant_type=client_credentials
    headers:
       Authorization: Basic TG1DbGllbnQ6cGFzczEyMw==
    validate_certs: no
  register: auth_response
- name: Get Assembly Status
  uri:
    method: GET
    url: https://ishtar:8280/api/topology/assemblies?nameContains={{ instance_name }}
    #environment:
    #  SSL_CERT_FILE:
    headers:
       Authorization: Bearer {{ auth_response.json.access_token }}
    validate_certs: no
  register: alm_response1
  
- name: Get token from kami
  uri:
    method: POST
    url: http://dish-tmf-adapter-svc:8289/KamiCore/oauth/token?grant_type=client_credentials
    headers:
       content-type: "application/json"
       Authorization: Basic ZGlzaDpkaXNoMTIzNA==
  register: token
  
  
- name: Get order id
  uri:
    method: GET
    url: http://dish-tmf-adapter-svc:8289/KamiCore/getExtOrderId
    return_content: yes
    body_format: json
    status_code: 201
    body: "{ \"alm_instance_name\": \"{{ alm_response1.json.assemblies[0].name }}\" }"
    headers:
       ReturnResultType: "FULL"
       Authorization: Bearer {{ token.json.access_token }}
    follow_redirects: yes
  register: kami_response
  



- name: Call RestAPI of SPML Adapter
  uri:
    url:  "http://dish-prov-ada-svc:8183/dish/ProvSpml/api/v1/spmlAdapter/modifyRemoveRequest"
    method: POST
    body: "{{lookup('template', 'nokia_provisioning_gw_data_roaming_cease_request.json.j2')}}"
    status_code: 200
    body_format: json
    headers:
      content-type: "application/json"
      ReturnResultType: "FULL"
  register: result

- name: fail instance if there is a failure from SBI
  fail:
    msg: Instance creation failed with error code {{ result.json.errorcode }} and error message {{ result.json.errormessage }}
  when: result.json.result == "failure"